"""Readable, pure-Python Z80 instruction-core reference implementation."""

from z80_python.console import CommandDebugger, CommandError, CommandResult
from z80_python.cpu import (
    FLAG_C,
    FLAG_H,
    FLAG_N,
    FLAG_PV,
    FLAG_S,
    FLAG_X,
    FLAG_Y,
    FLAG_Z,
    Z80CPU,
    CPUState,
    Flags,
)
from z80_python.debug import (
    BoundaryKind,
    DebugSession,
    DebugTarget,
    RunResult,
    StepRecord,
    StopReason,
)
from z80_python.disasm import ByteReader, Instruction, disassemble, disassemble_bytes
from z80_python.trace import (
    TRACE_SCHEMA_VERSION,
    TraceDifference,
    TraceDivergence,
    TraceValue,
    compare_step_records,
    first_trace_divergence,
    iter_trace_divergences,
    read_trace,
    step_record_from_dict,
    step_record_to_dict,
    write_trace,
)

__all__ = [
    "FLAG_C",
    "FLAG_H",
    "FLAG_N",
    "FLAG_PV",
    "FLAG_S",
    "FLAG_X",
    "FLAG_Y",
    "FLAG_Z",
    "TRACE_SCHEMA_VERSION",
    "Z80CPU",
    "BoundaryKind",
    "ByteReader",
    "CPUState",
    "CommandDebugger",
    "CommandError",
    "CommandResult",
    "DebugSession",
    "DebugTarget",
    "Flags",
    "Instruction",
    "RunResult",
    "StepRecord",
    "StopReason",
    "TraceDifference",
    "TraceDivergence",
    "TraceValue",
    "compare_step_records",
    "disassemble",
    "disassemble_bytes",
    "first_trace_divergence",
    "iter_trace_divergences",
    "read_trace",
    "step_record_from_dict",
    "step_record_to_dict",
    "write_trace",
]
